name: linters

on:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - '**'
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run GolangCI-Lint # https://github.com/golangci/golangci-lint
        run: docker run --rm -t -v $(pwd):/app -w /app golangci/golangci-lint:v1.48-alpine golangci-lint run -v
