name: linters

on:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - '**'
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
#          cache: true
          cache-dependency-path: "go.sum"

      - name: Run GolangCI-Lint # https://github.com/golangci/golangci-lint
        run: docker run --rm -t -v $(pwd):/app -w /app golangci/golangci-lint:v1.48-alpine golangci-lint run -v

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
#          cache: true
          cache-dependency-path: "go.sum"

      - name: Run Unit tests
        run: go test -v -race -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...

      - name: Clean test coverage
        run: cat coverage.out | grep -v -e "_easyjson.go" -e "main.go" > cover.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
